services:
  backend:
    image: sayan4444/book-management-system:latest
    environment:
      DB: root:password@tcp(db:3306)/book_management_system?charset=utf8mb4&parseTime=True&loc=Local
      PORT: 4000
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  db_data: